travis:
  secure:
    BINSTAR_TOKEN: gi2qpojLNAg8Qa1Nq0V9ADgx331KvepIBIAPgLKPqktDzfDOp8n9OwvD5LfW5nzzPTrwVcoWOqr2x9jMQRYDl7OcPn3h+FwHtBJSi+l6bApu6H+XbRfi7TkSh2vMIZNOxUlgRQM3gJ2Rb1UbqcXz0kQWxZwMddzBc2lxailOQeO9chUYf0EO7Y5wdO+hbg/2x3H5IK5Oy49rdmU+nl4y+ZXHjO86E010ufy45huAjeY3ATBVkFvbB5ZqPDcDFS82Kao2IJmicyWYSPQk+FksED7OWLK8DHTqKIDaZOGE+/0E/4GnA+oX8rc5Qj+lfEac66GgY/c9ezGh90cAf+wabd2tDdLB/Gzh/dGMeZNuGTwsLIOxl5Xv/y+v/IhghzO4fhfsnWVWwg7+hn+hWXBHQHoo2NwN2sqn716V0IZth7WfyjKpJqajKVfMEikVQR0fCu6+aifGVsrfdfzJJN0wixY0qL4xx6uU254Ig+O0gRwMPb+jAO3V33CfChnQBKatra3AHPwX5kgFLJwrnBrqLkkOtQL/023K+LD29AUxizy54XWMRNXnCGhmORzn2rSqqGZhLH5V073B2M3EnSGvaYu3woRgvNwjH770CjYWshtcJ3XifwoCDNbR05MbdeqzgkUUHBhjCRkwM8hsFpKn2nFkndYa62nRy7+K8pOHmLU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
